### ISSUE TITLE
KeyError on 'in_taxon'

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/cat-merge#15]
Hi cat-mergers - I have a new error that appeared somewhere between versions 0.1.7 and 0.1.11.

If I run any merge on an input without the `in_taxon` column, I get a `KeyError`:

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cat_merge.merge import merge
>>> merge(name='kg',nodes=['../BioPortal-to-KGX/transformed/ontologies/RDFS/RDFS_1_nodes.tsv', '../BioPortal-to-KGX/transformed/ontologies/BFO/BFO_2_nodes.tsv'],edges=['../BioPortal-to-KGX/transformed/ontologies/RDFS/RDFS_1_edges.tsv', '../BioPortal-to-KGX/transformed/ontologies/BFO/BFO_2_edges.tsv'])
Merging KG files...
  name: kg 
  input_dir: None 
  nodes: ['../BioPortal-to-KGX/transformed/ontologies/RDFS/RDFS_1_nodes.tsv', '../BioPortal-to-KGX/transformed/ontologies/BFO/BFO_2_nodes.tsv']
  edges: ['../BioPortal-to-KGX/transformed/ontologies/RDFS/RDFS_1_edges.tsv', '../BioPortal-to-KGX/transformed/ontologies/BFO/BFO_2_edges.tsv'] 
  mapping: None
  output_dir: merged-output

Reading node and edge files
Merging...
Generating QC report
Traceback (most recent call last):
  File "/home/harry/kg-env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'in_taxon'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harry/kg-env/lib/python3.8/site-packages/cat_merge/merge.py", line 59, in merge
    qc_report = create_qc_report(kg)
  File "/home/harry/kg-env/lib/python3.8/site-packages/cat_merge/qc_utils.py", line 88, in create_qc_report
    nodes['in_taxon'] = nodes['in_taxon'].fillna('missing taxon')
  File "/home/harry/kg-env/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/harry/kg-env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'in_taxon'
```

It looks like the qc_utils are looking for this column as part of report generation.

See also https://github.com/ncbo/kg-bioportal/issues/25

Would it be possible to omit this column from reports entirely?

**Comment by kevinschaper** [comment]
@caufieldjh gah! I just saw this, I'll fix it right away. I'll add a check for in_taxon, but also make the qc report optional, so that if there's anything else in there that's overfitted to monarch data it won't trip you up

**Comment by caufieldjh** [comment]
Thanks!
